### ISSUE TITLE
About the default root password

### ISSUE THREAD

**Issue by cbepx-me** [FlorianMarsch/rg35xxp-unchained#1]
The root user password for anbernic stock OS defaults to **root**

**Comment by FlorianMarsch** [comment]
thx I tried that and it didn't work for me, maybe my ssh config was not ok at that time. will test and adapt

**Comment by FlorianMarsch** [comment]
i removed the script and updated the readme

**Comment by cbepx-me** [comment]
Thank you for your excellent work
